apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  webserver
  labels:
    app: webserver
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "php-fpm"
      volumes:
        - name: source-codes
          emptyDir: {}
        - name: nginx-configuration
          configMap:
            name: nginx-configuration
            items:
            - key: nginx.conf
              path: default.conf
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
            - key: nginx.conf
              path: default.conf
      containers:
      - image: nginx:1.13.10-alpine
        name: nginx
        ports:
          - containerPort:  8080
            name: http
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
          - name: source-codes
            mountPath: /var/www/html
        lifecycle:
          preStop:
            exec:
              command:
              - nginx -s quit
      - image:
        name: php
        volumeMounts:
          - name: source-codes
            mountPath: /var/www/html
        #   - name: uploads
        #     mountPath: /app/uploads
        # # resources:
        # #   requests:
        # #     cpu: "20m"
        # #     memory: "55M"
        # # livenessProbe:
        # #   httpGet:
        # #     path: /_status/healthz
        # #     port: 5000
        # #   initialDelaySeconds: 90
        # #   timeoutSeconds: 10
        # # readinessProbe:
        # #   httpGet:
        # #     path: /_status/healthz
        # #     port: 5000
        # #   initialDelaySeconds: 30
        # #   timeoutSeconds: 10


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  webserver
  labels:
    app: webserver
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "php-fpm"
      volumes:
        # - name: source-codes
        #   hostPath:
        #     path: /home/docker/shopsys
        - name: nginx-configuration
          configMap:
            name: nginx-configuration
            items:
            - key: nginx.conf
              path: default.conf
        - name: php-configuration
          configMap:
            name: php-configuration
            items:
            - key: php-ini-overrides.ini
              path: php.ini
      containers:
      - image: nginx:1.13.10-alpine
        name: nginx
        ports:
          - containerPort: 8080
            name: http
        volumeMounts:
          - name: nginx-configuration
            mountPath: /etc/nginx/conf.d
          # - name: source-codes
          #   mountPath: /var/www/html
        lifecycle:
          preStop:
            exec:
              command:
              - nginx -s quit
      - image: $PHP_FPM_IMAGE
        name: php
        volumeMounts:
          - name: php-configuration
            mountPath: /usr/local/etc/php/php.ini
            subPath: php.ini
          # - name: source-codes
          #   mountPath: /var/www/html
